[package]
name = "dynomite-derive"
version = "0.1.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "derives dynamodb dynamoite types from native rust struct types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]
readme = "README.md"

[badges]
travis-ci = { repository = "softprops/dynomite" }

[lib]
proc-macro = true

[dependencies]
rusoto_dynamodb = "^0"
dynomite = { version = "0.0.0", path = "../dynomite" }
quote = "0.3"
syn = "0.11"

[dev-dependencies]
rusoto_core = "^0"
uuid = { version = "0.6", features = ["v4"] }