[package]
name = "dynomite"
version = "0.1.4"
authors = ["softprops <d.tangren@gmail.com>"]
description = "provides type conversions between dynamodb types and native rust types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]
readme = "../README.md"
documentation = "https://softprops.github.io/dynomite"
homepage = "https://github.com/softprops/dynomite"
repository = "https://github.com/softprops/dynomite"

[badges]
travis-ci = { repository = "softprops/dynomite" }
coveralls = { repository = "softprops/dynomite" }

[dependencies]
failure = "0.1"
futures = "0.1"
rusoto_core = "0.34"
rusoto_dynamodb = "0.34"
uuid = { version = "0.6", features = ["v4"], optional = true }

[features]
default = ["uuid"]