[package]
name = "dynomite"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "provides type conversions between dynamodb types and native rust types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]

[dependencies]
rusoto_core = "^0"
rusoto_dynamodb = "^0"
uuid = { version = "0.6", features = ["v4"], optional = true }

[features]
default = ["uuid"]